# -*- coding: utf-8 -*-
"""bq_in_jupyternotebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEHbqXMl5E5nT5ZUnzSSZjFsltTwK2SS
"""

# Commented out IPython magic to ensure Python compatibility.
# First, load the BigQuery magic command extension
# %load_ext google.cloud.bigquery

# Set Environment Variable in Python
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "key.json"

# Commented out IPython magic to ensure Python compatibility.
# # Execute a BigQuery query
# %%bigquery df --use_rest_api
# SELECT
#   depdelay as departure_delay,
#   COUNT(1) AS num_flights,
#   APPROX_QUANTILES(arrdelay, 10) AS arrival_delay_deciles
# FROM
#   `cloud-training-demos.airline_ontime_data.flights`
# WHERE
#  depdelay is not null
# GROUP BY
#   depdelay
# HAVING
#   num_flights > 100
# ORDER BY
#   depdelay ASC

# View the first five rows of the query's output
df.head()

# Display the DataFrame's information
df.info()